oleap:
  paths:
    api:
      countries: /api/common/countries
      languages: /api/common/languages
      phonetypes: /api/common/phonetypes
      salutations: /api/common/salutations
      subdivisions: /api/common/subdivisions